name: Bug Report
description: File a bug report to help us improve the project
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: E.g., Windows 10, macOS 12, Ubuntu 20.04
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: E.g., Chrome, Firefox, Safari
    validations:
      required: false
